class LoginPageLocators:
    ADMIN_BUTTON = "//*[@id='root']/header/div/div/a[2]"
    USERNAME_FIELD = '//*[@id=":r7:"]'
    PASSWORD_FIELD = '//*[@id=":r9:"]'
    SUBMIT_BUTTON = '//*[@id="auth-tabpanel-0"]/div/form/button'
    LOGOUT = "//*[contains(text(),'Logout')]"
    INVALID_CREDENTIALS_MESSAGE = "//*[contains(text(),'Invalid credentials')]"
    BLOG_POST_BUTTON = "//*[contains(text(),'New Blog Post')]"
    TITLE_CHECK = "//label[contains(text(),'Title')]/following::input[1]"
    EXCERPT_CHECK = "//label[contains(text(),'Excerpt')]/following::textarea[1]"
    CONTENT_CHECK = "//*[@id='root']/div/div/form/div[4]/div/div[2]/div[1]"
    CONTENT_CLICK = '//*[contains(text(),"Content")]'
    # CONTENT_CHECK = "//*[@id='root']/div/div/form/div[4]/div/div[2]/div[1]"
    CATEGORY_CHECK = "//label[contains(text(),'Category')]/following::div[1]"
    CATEGORY_OPTION = "//*[contains(text(),'Technology')]"
    TAGS_CHECK = "//label[contains(text(),'Tags')]/following::div[1]"
    TAGS_CHECK_OPTION_1 = "//*[contains(text(),'JavaScript')]"
    TAGS_CHECK_OPTION_2 = "//*[contains(text(),'TypeScript')]"
    TAGS_CHECK_OPTION_3 = "//*[contains(text(),'React')]"
    TAGS_CHECK_OPTION_4 = "//*[contains(text(),'Node.js')]"
    PUBLISH_NOW_BUTTON = "//*[contains(text(),'Publish Now')]"
    SAVE_BUTTON = "//*[contains(text(),'Save')]"
    CANCEL_BUTTON = "//*[contains(text(),'Cancel')]"
    TEST_TITLE_CREATED = "//td[contains(text(),'Test Title')]"
    DELETE_ICON = "//*[@id='root']/div/div[2]/table/tbody/tr[1]/td[8]/button[3]"
    CONFIRM_DELETE_BUTTON = "//button[contains(text(),'Delete') and not(contains(text(),'Cancel'))] | //button[@type='button' and contains(text(),'Delete')]"
    CANCEL_DELETE_BUTTON = "//button[contains(text(),'Cancel')]"
    DASHBOARD_TITLE = "//a[contains(text(),'Dashboard')]"
    DELETE_BUTTON = "//button[@data-testid='confirm-delete-button']"
    HOME_BUTTON = "//a[contains(text(),'Home')]"
    SEARCH_INPUT = "//*[@id=':r3:']"
    SEARCH_BUTTON = "//button[contains(@aria-label,'Search')] | //button[@type='submit']"
    NO_BLOGS_FOUND = "//*[contains(text(),'No blogs found')] | //*[contains(text(),'No Blogs Found')] | //*[contains(text(),'No results found')]"
    BLOG_CARD = "//article | //div[contains(@class,'blog')] | //div[contains(@class,'card')] | //*[contains(@data-testid,'blog')]"
    BLOG_CARD_TITLE = "//h2[contains(text(),'Getting Started with TypeScript')]"
    SWITCH_TO_DARK_MODE_BUTTON = "//*[@id='root']/header/div/div/button"
    READMORE_BUTTON = "//button[contains(text(),'Read More')]"
    DARK_MODE_ACTIVE_BUTTON = "//*[@id='root']/header/div/div/button"
